version: ~> 1.0
os: linux
dist: bionic
language: node_js
install:
  - npm ci
script:
  # Test Git hooks in CI, to make sure script upgrades do not break them.
  - npm run prepare
  - ./.git/hooks/pre-commit
  - npm run test:ci
branches:
  except:
    - gh-pages
notifications:
  email: false
