sudo: false
language: node_js
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run test:ci
  - npx commitlint-travis
branches:
  except:
    - gh-pages
notifications:
  email: false
